// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/service/internal/dao/internal"
)

// blogWebsiteDao is the data access object for table blog_website.
// You can define custom methods on it to extend its functionality as you wish.
type blogWebsiteDao struct {
	*internal.BlogWebsiteDao
}

var (
	// BlogWebsite is globally public accessible object for table blog_website operations.
	BlogWebsite = blogWebsiteDao{
		internal.NewBlogWebsiteDao(),
	}
)

// Fill with you ideas below.
