// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/service/internal/dao/internal"
)

// blogCategoryDao is the data access object for table blog_category.
// You can define custom methods on it to extend its functionality as you wish.
type blogCategoryDao struct {
	*internal.BlogCategoryDao
}

var (
	// BlogCategory is globally public accessible object for table blog_category operations.
	BlogCategory = blogCategoryDao{
		internal.NewBlogCategoryDao(),
	}
)

// Fill with you ideas below.
