// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/service/internal/dao/internal"
)

// blogArticleDao is the data access object for table blog_article.
// You can define custom methods on it to extend its functionality as you wish.
type blogArticleDao struct {
	*internal.BlogArticleDao
}

var (
	// BlogArticle is globally public accessible object for table blog_article operations.
	BlogArticle = blogArticleDao{
		internal.NewBlogArticleDao(),
	}
)

// Fill with you ideas below.
