// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/service/internal/dao/internal"
)

// blogCommentDao is the data access object for table blog_comment.
// You can define custom methods on it to extend its functionality as you wish.
type blogCommentDao struct {
	*internal.BlogCommentDao
}

var (
	// BlogComment is globally public accessible object for table blog_comment operations.
	BlogComment = blogCommentDao{
		internal.NewBlogCommentDao(),
	}
)

// Fill with you ideas below.
