// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogComment is the golang structure of table blog_comment for DAO operations like Where/Data.
type BlogComment struct {
	g.Meta    `orm:"table:blog_comment, do:true"`
	Id        interface{} // 评论id
	Content   interface{} // 评论内容
	Nickname  interface{} // 评论者名称
	Email     interface{} // 评论者邮箱
	ArticleId interface{} // 文章id
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
