// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BlogCategory is the golang structure of table blog_category for DAO operations like Where/Data.
type BlogCategory struct {
	g.Meta `orm:"table:blog_category, do:true"`
	Id     interface{} // 分类id
	Name   interface{} // 分类名称
}
