// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogArticle is the golang structure of table blog_article for DAO operations like Where/Data.
type BlogArticle struct {
	g.Meta     `orm:"table:blog_article, do:true"`
	Id         interface{} // 文章id
	Author     interface{} // 作者
	Cover      interface{} // 文章封面
	Title      interface{} // 文章标题
	Summary    interface{} // 文章摘要
	Content    interface{} // 文章内容
	Visit      interface{} // 文章阅读量
	Support    interface{} // 文章点赞量
	CategoryId interface{} // 文章分类id
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 更新时间
	DeletedAt  *gtime.Time // 删除时间
}
