// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BlogWebsite is the golang structure of table blog_website for DAO operations like Where/Data.
type BlogWebsite struct {
	g.Meta    `orm:"table:blog_website, do:true"`
	Id        interface{} // 网站id
	Name      interface{} // 网站名称
	Logo      interface{} // 网站LOGO
	Copyright interface{} // 网站版权
}
