// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogUser is the golang structure of table blog_user for DAO operations like Where/Data.
type BlogUser struct {
	g.Meta    `orm:"table:blog_user, do:true"`
	Id        interface{} // 主键id
	Username  interface{} // 用户名
	Password  interface{} // 用户密码
	Status    interface{} // 用户状态（0：关闭、1：开启）
	Salt      interface{} // 用户密码加盐
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	RoleType  interface{} // 用户角色 0普通用户 1管理员
}
