// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogUser is the golang structure for table blog_user.
type BlogUser struct {
	Id        uint        `json:"id"        ` // 主键id
	Username  string      `json:"username"  ` // 用户名
	Password  string      `json:"password"  ` // 用户密码
	Status    int         `json:"status"    ` // 用户状态（0：关闭、1：开启）
	Salt      string      `json:"salt"      ` // 用户密码加盐
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 更新时间
	RoleType  int         `json:"roleType"  ` // 用户角色 0普通用户 1管理员
}
