// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package entity

// BlogCategory is the golang structure for table blog_category.
type BlogCategory struct {
	Id   uint   `json:"id"   ` // 分类id
	Name string `json:"name" ` // 分类名称
}
