// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package entity

// BlogWebsite is the golang structure for table blog_website.
type BlogWebsite struct {
	Id        uint   `json:"id"        ` // 网站id
	Name      string `json:"name"      ` // 网站名称
	Logo      string `json:"logo"      ` // 网站LOGO
	Copyright string `json:"copyright" ` // 网站版权
}
