// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogArticle is the golang structure for table blog_article.
type BlogArticle struct {
	Id         uint        `json:"id"         ` // 文章id
	Author     string      `json:"author"     ` // 作者
	Cover      string      `json:"cover"      ` // 文章封面
	Title      string      `json:"title"      ` // 文章标题
	Summary    string      `json:"summary"    ` // 文章摘要
	Content    string      `json:"content"    ` // 文章内容
	Visit      uint        `json:"visit"      ` // 文章阅读量
	Support    uint        `json:"support"    ` // 文章点赞量
	CategoryId uint        `json:"categoryId" ` // 文章分类id
	CreatedAt  *gtime.Time `json:"createdAt"  ` // 创建时间
	UpdatedAt  *gtime.Time `json:"updatedAt"  ` // 更新时间
	DeletedAt  *gtime.Time `json:"deletedAt"  ` // 删除时间
}
