// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-07-08 20:05:29
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlogCommentDao is the data access object for table blog_comment.
type BlogCommentDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns BlogCommentColumns // columns contains all the column names of Table for convenient usage.
}

// BlogCommentColumns defines and stores column names for table blog_comment.
type BlogCommentColumns struct {
	Id        string // 评论id
	Content   string // 评论内容
	Nickname  string // 评论者名称
	Email     string // 评论者邮箱
	ArticleId string // 文章id
	CreatedAt string // 创建时间
	UpdatedAt string // 更新时间
	DeletedAt string // 删除时间
}

//  blogCommentColumns holds the columns for table blog_comment.
var blogCommentColumns = BlogCommentColumns{
	Id:        "id",
	Content:   "content",
	Nickname:  "nickname",
	Email:     "email",
	ArticleId: "article_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewBlogCommentDao creates and returns a new DAO object for table data access.
func NewBlogCommentDao() *BlogCommentDao {
	return &BlogCommentDao{
		group:   "default",
		table:   "blog_comment",
		columns: blogCommentColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlogCommentDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlogCommentDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlogCommentDao) Columns() BlogCommentColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlogCommentDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlogCommentDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlogCommentDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
